In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('sonar data.csv')

In [3]:
df.head()

,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
0,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
1,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
2,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
3,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R
4,0.0286,0.0453,0.0277,0.0174,0.0384,0.0990,0.1201,0.1833,0.2105,0.3039,...,0.0045,0.0014,0.0038,0.0013,0.0089,0.0057,0.0027,0.0051,0.0062,R

In [4]:
df.shape

(207, 61)

In [5]:
df.describe()

,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0232,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032
count,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,...,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000
mean,0.029208,0.038443,0.043837,0.054053,0.075105,0.104599,0.121591,0.134677,0.177361,0.208245,...,0.016034,0.013472,0.010729,0.010917,0.009300,0.008181,0.007771,0.007947,0.007936,0.006523
std,0.023038,0.033040,0.038521,0.046583,0.055669,0.059247,0.061897,0.085340,0.118311,0.134741,...,0.012027,0.009628,0.007071,0.007310,0.007103,0.005719,0.005756,0.006485,0.006196,0.005038
min,0.001500,0.000600,0.001500,0.005800,0.006700,0.010200,0.003300,0.005500,0.007500,0.011300,...,0.000000,0.000800,0.000500,0.001000,0.000600,0.000400,0.000300,0.000300,0.000100,0.000600
25%,0.013300,0.016400,0.018900,0.024450,0.037700,0.066950,0.080600,0.080350,0.096750,0.111150,...,0.008350,0.007350,0.005050,0.005350,0.004100,0.004400,0.003700,0.003600,0.003650,0.003100
50%,0.022800,0.030800,0.034200,0.044100,0.062000,0.092100,0.105600,0.111900,0.152200,0.181000,...,0.013800,0.011500,0.009600,0.009300,0.007500,0.006800,0.005900,0.005800,0.006300,0.005300
75%,0.035800,0.048100,0.058200,0.065700,0.101050,0.134150,0.153050,0.169800,0.231500,0.269000,...,0.020700,0.016750,0.014900,0.014450,0.012100,0.010350,0.010350,0.010400,0.010350,0.008550
max,0.137100,0.233900,0.305900,0.426400,0.401000,0.382300,0.372900,0.459000,0.682800,0.710600,...,0.100400,0.070900,0.039000,0.035200,0.044700,0.039400,0.035500,0.044000,0.036400,0.043900

In [6]:
df.value_counts()

0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109  0.2111  0.1609  0.1582  0.2238  0.0645  0.0660  0.2273  0.3100  0.2999  0.5078  0.4797  0.5783  0.5071  0.4328  0.5550  0.6711  0.6415  0.7104  0.8080  0.6791  0.3857  0.1307  0.2604  0.5121  0.7547  0.8537  0.8507  0.6692  0.6097  0.4943  0.2744  0.0510  0.2834  0.2825  0.4256  0.2641  0.1386  0.1051  0.1343  0.0383  0.0324  0.0232  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084  0.0090  0.0032  R
0.0015  0.0186  0.0289  0.0195  0.0515  0.0817  0.1005  0.0124  0.1168  0.1476  0.2118  0.2575  0.2354  0.1334  0.0092  0.1951  0.3685  0.4646  0.5418  0.6260  0.7420  0.8257  0.8609  0.8400  0.8949  0.9945  1.0000  0.9649  0.8747  0.6257  0.2184  0.2945  0.3645  0.5012  0.7843  0.9361  0.8195  0.6207  0.4513  0.3004  0.2674  0.2241  0.3141  0.3693  0.2986  0.2226  0.0849  0.0359  0.0289  0.0122  0.0045  0.0108  0.0075  0.0089  0.0036  0.0029  0.0013  0.0010  0.0032  0.0047  M    1
0.0315  0.0252  0.0167  0.0479  0.0902  0.1057  0.1024  0.1209  0.1241  0.1533  0.2128  0.2536  0.2686  0.2803  0.1886  0.1485  0.2160  0.2417  0.2989  0.3341  0.3786  0.3956  0.5232  0.6913  0.7868  0.8337  0.9199  1.0000  0.8990  0.6456  0.5967  0.4355  0.2997  0.2294  0.1866  0.0922  0.1829  0.1743  0.2452  0.2407  0.2518  0.3184  0.1685  0.0675  0.1186  0.1833  0.1878  0.1114  0.0310  0.0143  0.0138  0.0108  0.0062  0.0044  0.0072  0.0007  0.0054  0.0035  0.0001  0.0055  M    1
0.0293  0.0644  0.0390  0.0173  0.0476  0.0816  0.0993  0.0315  0.0736  0.0860  0.0414  0.0472  0.0835  0.0938  0.1466  0.0809  0.1179  0.2179  0.3326  0.3258  0.2111  0.2302  0.3361  0.4259  0.4609  0.2606  0.0874  0.2862  0.5606  0.8344  0.8096  0.7250  0.8048  0.9435  1.0000  0.8960  0.5516  0.3037  0.2338  0.2382  0.3318  0.3821  0.1575  0.2228  0.1582  0.1433  0.1634  0.1133  0.0567  0.0133  0.0170  0.0035  0.0052  0.0083  0.0078  0.0075  0.0105  0.0160  0.0095  0.0011  R    1
0.0294  0.0123  0.0117  0.0113  0.0497  0.0998  0.1326  0.1117  0.2984  0.3473  0.4231  0.5044  0.5237  0.4398  0.3236  0.2956  0.3286  0.3231  0.4528  0.6339  0.7044  0.8314  0.8449  0.8512  0.9138  0.9985  1.0000  0.7544  0.4661  0.3924  0.3849  0.4674  0.4245  0.3095  0.0752  0.2885  0.4072  0.3170  0.2863  0.2634  0.0541  0.1874  0.3459  0.4646  0.4366  0.2581  0.1319  0.0505  0.0112  0.0059  0.0041  0.0056  0.0104  0.0079  0.0014  0.0054  0.0015  0.0006  0.0081  0.0043  M    1
0.0298  0.0615  0.0650  0.0921  0.1615  0.2294  0.2176  0.2033  0.1459  0.0852  0.2476  0.3645  0.2777  0.2826  0.3237  0.4335  0.5638  0.4555  0.4348  0.6433  0.3932  0.1989  0.3540  0.9165  0.9371  0.4620  0.2771  0.6613  0.8028  0.4200  0.5192  0.6962  0.5792  0.8889  0.7863  0.7133  0.7615  0.4401  0.3009  0.3163  0.2809  0.2898  0.0526  0.1867  0.1553  0.1633  0.1252  0.0748  0.0452  0.0064  0.0154  0.0031  0.0153  0.0071  0.0212  0.0076  0.0152  0.0049  0.0200  0.0073  R    1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ..
0.0189  0.0308  0.0197  0.0622  0.0080  0.0789  0.1440  0.1451  0.1789  0.2522  0.2607  0.3710  0.3906  0.2672  0.2716  0.4183  0.6988  0.5733  0.2226  0.2631  0.7473  0.7263  0.3393  0.2824  0.6053  0.5897  0.4967  0.8616  0.8339  0.4084  0.2268  0.1745  0.0507  0.1588  0.3040  0.1369  0.1605  0.2061  0.0734  0.0202  0.1638  0.1583  0.1830  0.1886  0.1008  0.0663  0.0183  0.0404  0.0108  0.0143  0.0091  0.0038  0.0096  0.0142  0.0190  0.0140  0.0099  0.0092  0.0052  0.0075  R    1
0.0190  0.0038  0.0642  0.0452  0.0333  0.0690  0.0901  0.1454  0.0740  0.0349  0.1459  0.3473  0.3197  0.2823  0.0166  0.0572  0.2164  0.4563  0.3819  0.5627  0.6484  0.7235  0.8242  0.8766  1.0000  0.8582  0.6563  0.5087  0.4817  0.4530  0.4521  0.4532  0.5385  0.5308  0.5356  0.5271  0.4260  0.2436  0.1205  0.3845  0.4107  0.5067  0.4216  0.2479  0.1586  0.1124  0.0651  0.0789  0.0325  0.0070  0.0026  0.0093  0.0118  0.0112  0.0094  0.0140  0.0072  0.0022  0.0055  0.0122  R    1
0.0191  0.0173  0.0291  0.0301  0.0463  0.0690  0.0576  0.1103  0.2423  0.3134  0.4786  0.5239  0.4393  0.3440  0.2869  0.3889  0.4420  0.3892  0.4088  0.5006  0.7271  0.9385  1.0000  0.9831  0.9932  0.9161  0.8237  0.6957  0.4536  0.3281  0.2522  0.3964  0.4154  0.3308  0.1445  0.1923  0.3208  0.3367  0.5683  0.5505  0.3231  0.0448  0.3131  0.3387  0.4130  0.3639  0.2069  0.0859  0.0600  0.0267  0.0125  0.0040  0.0136  0.0137  0.0172  0.0132  0.0110  0.0122  0.0114  0.0068  M    1
0.0192  0.0607  0.0378  0.0774  0.1388  0.0809  0.0568  0.0219  0.1037  0.1186  0.1237  0.1601  0.3520  0.4479  0.3769  0.5761  0.6426  0.6790  0.7157  0.5466  0.5399  0.6362  0.7849  0.7756  0.5780  0.4862  0.4181  0.2457  0.0716  0.0613  0.1816  0.4493  0.5976  0.3785  0.2495  0.5771  0.8852  0.8409  0.3570  0.3133  0.6096  0.6378  0.2709  0.1419  0.1260  0.1288  0.0790  0.0829  0.0520  0.0216  0.0360  0.0331  0.0131  0.0120  0.0108  0.0024  0.0045  0.0037  0.0112  0.0075  R    1
0.1371  0.1226  0.1385  0.1484  0.1776  0.1428  0.1773  0.2161  0.1630  0.2067  0.4257  0.5484  0.7131  0.7003  0.6777  0.7939  0.9382  0.8925  0.9146  0.7832  0.7960  0.7983  0.7716  0.6615  0.4860  0.5572  0.4697  0.5640  0.4517  0.3369  0.2684  0.2339  0.3052  0.3016  0.2753  0.1041  0.1757  0.3156  0.3603  0.2736  0.1301  0.2458  0.3404  0.1753  0.0679  0.1062  0.0643  0.0532  0.0531  0.0272  0.0171  0.0118  0.0129  0.0344  0.0065  0.0067  0.0022  0.0079  0.0146  0.0051  M    1
Length: 207, dtype: int64

In [7]:
df['R'].value_counts()

M    111
R     96
Name: R, dtype: int64

In [8]:
df.groupby('R').mean()

,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0232,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032
R,,,,,,,,,,,,,,,,,,,,,
M,0.034989,0.045544,0.050720,0.064768,0.086715,0.111864,0.128359,0.149832,0.213492,0.251022,...,0.019352,0.016014,0.011643,0.012185,0.009923,0.008914,0.007825,0.009060,0.008695,0.006930
R,0.022524,0.030232,0.035879,0.041664,0.061680,0.096199,0.113767,0.117153,0.135584,0.158785,...,0.012198,0.010533,0.009673,0.009451,0.008581,0.007333,0.007708,0.006659,0.007058,0.006053

In [9]:
X= df.drop(columns='R', axis=1)
y= df['R']

In [10]:
print(X)
print(y)

     0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109  \
0    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337
1    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598
2    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598
3    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564
4    0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105
..      ...     ...     ...     ...     ...     ...     ...     ...     ...
202  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328
203  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030
204  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258
205  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945
206  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843

     0.2111  ...  0.0232  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  \
0    0.2872  ...  0.0125  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140
1    0.6194  ...  0.0033  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316
2    0.1264  ...  0.0241  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050
3    0.4459  ...  0.0156  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072
4    0.3039  ...  0.0104  0.0045  0.0014  0.0038  0.0013  0.0089  0.0057
..      ...  ...     ...     ...     ...     ...     ...     ...     ...
202  0.2684  ...  0.0203  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065
203  0.2154  ...  0.0051  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034
204  0.2529  ...  0.0155  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140
205  0.2354  ...  0.0042  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034
206  0.2354  ...  0.0181  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040

     0.0084  0.0090  0.0032
0    0.0049  0.0052  0.0044
1    0.0164  0.0095  0.0078
2    0.0044  0.0040  0.0117
3    0.0048  0.0107  0.0094
4    0.0027  0.0051  0.0062
..      ...     ...     ...
202  0.0115  0.0193  0.0157
203  0.0032  0.0062  0.0067
204  0.0138  0.0077  0.0031
205  0.0079  0.0036  0.0048
206  0.0036  0.0061  0.0115

[207 rows x 60 columns]
0      R
1      R
2      R
3      R
4      R
      ..
202    M
203    M
204    M
205    M
206    M
Name: R, Length: 207, dtype: object

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, stratify=y, random_state=1)

In [12]:
print(X.shape, X_train.shape, X_test.shape)

(207, 60) (186, 60) (21, 60)

In [13]:
print(X_train)
print(y_train)

     0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109  \
114  0.0414  0.0436  0.0447  0.0844  0.0419  0.1215  0.2002  0.1516  0.0818
65   0.0265  0.0440  0.0137  0.0084  0.0305  0.0438  0.0341  0.0780  0.0844
16   0.0192  0.0607  0.0378  0.0774  0.1388  0.0809  0.0568  0.0219  0.1037
122  0.0270  0.0163  0.0341  0.0247  0.0822  0.1256  0.1323  0.1584  0.2017
36   0.0333  0.0221  0.0270  0.0481  0.0679  0.0981  0.0843  0.1172  0.0759
..      ...     ...     ...     ...     ...     ...     ...     ...     ...
139  0.0412  0.1135  0.0518  0.0232  0.0646  0.1124  0.1787  0.2407  0.2682
15   0.0352  0.0116  0.0191  0.0469  0.0737  0.1185  0.1683  0.1541  0.1466
153  0.0117  0.0069  0.0279  0.0583  0.0915  0.1267  0.1577  0.1927  0.2361
130  0.1150  0.1163  0.0866  0.0358  0.0232  0.1267  0.2417  0.2661  0.4346
202  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328

     0.2111  ...  0.0232  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  \
114  0.1975  ...  0.0222  0.0045  0.0136  0.0113  0.0053  0.0165  0.0141
65   0.0779  ...  0.0100  0.0038  0.0187  0.0156  0.0068  0.0097  0.0073
16   0.1186  ...  0.0360  0.0331  0.0131  0.0120  0.0108  0.0024  0.0045
122  0.2122  ...  0.0197  0.0189  0.0204  0.0085  0.0043  0.0092  0.0138
36   0.0920  ...  0.0036  0.0022  0.0032  0.0060  0.0054  0.0063  0.0143
..      ...  ...     ...     ...     ...     ...     ...     ...     ...
139  0.2058  ...  0.0798  0.0376  0.0143  0.0272  0.0127  0.0166  0.0095
15   0.2912  ...  0.0426  0.0346  0.0158  0.0154  0.0109  0.0048  0.0095
153  0.2169  ...  0.0039  0.0053  0.0029  0.0020  0.0013  0.0029  0.0020
130  0.5378  ...  0.0228  0.0099  0.0065  0.0085  0.0166  0.0110  0.0190
202  0.2684  ...  0.0203  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065

     0.0084  0.0090  0.0032
114  0.0077  0.0246  0.0198
65   0.0081  0.0086  0.0095
16   0.0037  0.0112  0.0075
122  0.0094  0.0105  0.0093
36   0.0132  0.0051  0.0041
..      ...     ...     ...
139  0.0225  0.0098  0.0085
15   0.0015  0.0073  0.0067
153  0.0062  0.0026  0.0052
130  0.0141  0.0068  0.0086
202  0.0115  0.0193  0.0157

[186 rows x 60 columns]
114    M
65     R
16     R
122    M
36     R
      ..
139    M
15     R
153    M
130    M
202    M
Name: R, Length: 186, dtype: object

In [14]:
model= LogisticRegression()

In [15]:
model.fit(X_train, y_train)

LogisticRegression()

In [16]:
X_train_pred= model.predict(X_train)
training_data_accuracy= accuracy_score(X_train_pred, y_train)

In [17]:
print('accuracy on training data is :', training_data_accuracy)

accuracy on training data is : 0.8440860215053764

In [18]:
X_test_pred= model.predict(X_test)
testing_data_accuracy= accuracy_score(X_test_pred, y_test)

In [19]:
print('accuracy on testing data is :', testing_data_accuracy)

accuracy on testing data is : 0.7619047619047619

In [20]:
input_data= (0.0123,0.0309,0.0169,0.0313,0.0358,0.0102,0.0182,0.0579,0.1122,0.0835,0.0548,0.0847,0.2026,0.2557,0.1870,0.2032,0.1463,0.2849,0.5824,0.7728,0.7852,0.8515,0.5312,0.3653,0.5973,0.8275,1.0000,0.8673,0.6301,0.4591,0.3940,0.2576,0.2817,0.2641,0.2757,0.2698,0.3994,0.4576,0.3940,0.2522,0.1782,0.1354,0.0516,0.0337,0.0894,0.0861,0.0872,0.0445,0.0134,0.0217,0.0188,0.0133,0.0265,0.0224,0.0074,0.0118,0.0026,0.0092,0.0009,0.0044)
input_data_as_numpy_array = np.asarray(input_data)
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
prediction = model.predict(input_data_reshaped)
print(prediction)

if (prediction[0]=='R'):
    print('The Opject Is Rock')
else:
    print('The Opject Is Mine')

['R']
The Opject Is Rock

C:\Users\Ibrahim K. Gamal\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [21]:
input_data= (0.0346,0.0509,0.0079,0.0243,0.0432,0.0735,0.0938,0.1134,0.1228,0.1508,0.1809,0.2390,0.2947,0.2866,0.4010,0.5325,0.5486,0.5823,0.6041,0.6749,0.7084,0.7890,0.9284,0.9781,0.9738,1.0000,0.9702,0.9956,0.8235,0.6020,0.5342,0.4867,0.3526,0.1566,0.0946,0.1613,0.2824,0.3390,0.3019,0.2945,0.2978,0.2676,0.2055,0.2069,0.1625,0.1216,0.1013,0.0744,0.0386,0.0050,0.0146,0.0040,0.0122,0.0107,0.0112,0.0102,0.0052,0.0024,0.0079,0.0031)
input_data_as_numpy_array = np.asarray(input_data)
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
prediction = model.predict(input_data_reshaped)
print(prediction)

if (prediction[0]=='R'):
    print('The Opject Is Rock')
else:
    print('The Opject Is Mine')

['M']
The Opject Is Mine

C:\Users\Ibrahim K. Gamal\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(